name: Badge generator

on:
  push:
    paths:
      - "apps/gha-badge-generator/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Build with Maven
        working-directory: apps/gha-badge-generator
        run: mvn --batch-mode package

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: apps/gha-badge-generator
          push: false
          tags: user/app:latest
