name: Badge generator

on:
  push:
    paths:
      - "apps/gha-badge-generator/**"
    branches:
      - main
  pull_request:
    paths:
      - "apps/gha-badge-generator/**"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-west-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          cache: "maven"

      - name: Build with Maven
        working-directory: apps/gha-badge-generator
        run: mvn --batch-mode package

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: apps/gha-badge-generator
          push: ${{ github.ref_name == 'main' }}
          tags: 372466110691.dkr.ecr.eu-west-1.amazonaws.com/hackaton-badge-generator:${{ github.sha }}
