name: Badge generator

on:
  push:
    paths:
      - "apps/gha-badge-generator/**"
      - ".github/workflows/gha-badge-generator.yml"
    branches:
      - main
  pull_request:
    paths:
      - "apps/gha-badge-generator/**"
      - ".github/workflows/gha-badge-generator.yml"

concurrency: ${{ github.ref_name || github.run_id }}

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-west-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          cache: "maven"

      - name: Build with Maven
        working-directory: apps/gha-badge-generator
        run: mvn --batch-mode package

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build (and push when on main)
        uses: docker/build-push-action@v3
        with:
          context: apps/gha-badge-generator
          push: ${{ github.ref_name == 'main' }}
          tags: 372466110691.dkr.ecr.eu-west-1.amazonaws.com/hackaton-badge-generator:${{ github.sha }}

      - name: Deploy to App Runner
        if: ${{ github.ref_name == 'main' }}
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: badge-generator
          image: 372466110691.dkr.ecr.eu-west-1.amazonaws.com/hackaton-badge-generator:${{ github.sha }}
          access-role-arn: arn:aws:iam::372466110691:role/service-role/HackatonVBadgeAppRunnerECRAccessRole
          region: ${{ env.AWS_REGION }}
          cpu : 1
          memory : 2
          wait-for-service-stability: true
