name: Web UI

on:
  push:
    paths:
      - "apps/gha-web-ui/**"
      - ".github/workflows/gha-web-ui.yml"
    branches:
      - main
  pull_request:
    paths:
      - "apps/gha-web-ui/**"
      - ".github/workflows/gha-web-ui.yml"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    defaults:
      run:
        shell: bash
        working-directory: apps/gha-web-ui

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.8.0"
          cache: 'npm'
          cache-dependency-path: apps/gha-web-ui/package-lock.json

      - run: npm ci

      - run: npm run ng build

      - name: Setup Pages
        if: github.ref_name == 'main'
        uses: actions/configure-pages@v2

      - name: Upload artifact
        if: github.ref_name == 'main'
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'apps/gha-web-ui/dist/gha-web-ui/'

      - name: Deploy to GitHub Pages
        if: github.ref_name == 'main'
        id: deployment
        uses: actions/deploy-pages@v1
