name: Web UI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "apps/gha-web-ui/**"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-west-1

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apps/gha-web-ui

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.8.0"
          cache: 'npm'
          cache-dependency-path: apps/gha-web-ui/package-lock.json

      - run: yarn global add @angular/cli

      - run: npm ci

      - run: ng build
        if: github.ref_name != 'main'

      - run: ng deploy
        if: github.ref_name == 'main'
        env:
          NG_DEPLOY_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          NG_DEPLOY_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NG_DEPLOY_AWS_REGION: eu-west-1
          NG_DEPLOY_AWS_BUCKET: hackaton-v-ui
