name: Web UI

on:
  push:
    paths:
      - "apps/gha-web-ui/**"
      - ".github/workflows/gha-web-ui.yml"
    branches:
      - main
  pull_request:
    paths:
      - "apps/gha-web-ui/**"
      - ".github/workflows/gha-web-ui.yml"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-west-1

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apps/gha-web-ui

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.8.0"
          cache: 'npm'
          cache-dependency-path: apps/gha-web-ui/package-lock.json

      - run: yarn global add @angular/cli

      - run: npm ci

      - run: ng build

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'apps/gha-web-ui/dist/gha-web-ui/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
