name: test-debug-with-upterm

on:
  push:
    branches:
      - test-debug-ssh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      with:
        limit-access-to-actor: true
      timeout-minutes: 1
